### PR TITLE
Finished FRAM prototype

### PR DESCRIPTION
**Pull request by snowy-shadow**
I can explain the code to you next week if you want

### CODE REVIEW

**Comment by snowy-shadow** [comment]
also yes, the code is very jank

**Comment by frroossst** [comment]
Is this just the test for FRAM or code that wraps data for writing to the FRAM?

**Comment by snowy-shadow** [comment]
this is the prototype for writing and reading to the fram. it is not C compatible tho. It is fully c++

**Comment by frroossst** [comment]
Next Saturday, I need to talk to you about the memory layout of floats, some floats can be made restrictive like temperature, as we don't need the full range there, perhaps for things like acceleration we'll utilise the full range of 32 bits. We need to narrow down what needs all 32 bits and what doesn't. For example, gyroscopic data wouldn't need the full 32 bits.

**Pull request closed without merging**
